### ISSUE TITLE
TextView UI is updated in a AsyncTask

### ISSUE THREAD

**Issue by kbumsik** [cjackie/ActivitiesPrediction#2]
Currently the `CommTask` class in the mobile app updates two TextView instances. Clearly this is not a good class design. It is not an urgent task but we should move it the the main UI task someday. We can achieve that using [IPC between threads](https://developer.android.com/training/multiple-threads/communicate-ui.html#Handler)

**Comment by cjackie** [comment]
I will take over the ownership of CommTask class. Java side should be easier for me to handle.
