### ISSUE TITLE
Migrate Data into Database

### ISSUE THREAD

**Issue by cjackie** [cjackie/ActivitiesPrediction#4]
@kbumsik 
Can you create scripts to migrate data into the dabtabase? Shoaib_data_set, and my_data.

**Comment by cjackie** [comment]
see #5 too. I think it is better that you do this.

**Comment by cjackie** [comment]
This is low priority. I think I will do this one.

**Comment by kbumsik** [comment]
It is already possible. [See this](https://github.com/cjackie/ActivitiesPrediction/tree/master/Backend/scripts)

The usage of this is:
> python connection_test.py sample_dataset.csv
