### ISSUE TITLE
Split DataSet

### ISSUE THREAD

**Issue by cjackie** [cjackie/ActivitiesPrediction#6]
currently DataSet is:
```python
class DataSet(Base):
    __tablename__ = 'DataSet'

    id = Column(Integer, primary_key=True)
    label_id = Column(Integer, ForeignKey('ActivityLabel.id'))
    position_id = Column(Integer, ForeignKey('BodyPosition.id'))
    timestamp = Column(Integer, nullable=False)
    ax = Column(Float, nullable=False)
    ay = Column(Float, nullable=False)
    az = Column(Float, nullable=False)
    gx = Column(Float, nullable=False)
    gy = Column(Float, nullable=False)
    gz = Column(Float, nullable=False)
    mx = Column(Float, nullable=False)
    my = Column(Float, nullable=False)
    mz = Column(Float, nullable=False)
```

But we need to split this class into two classes:
- accelerometer data
- gyroscope data

We don't need `mx`, `my`, `mz`

**Comment by kbumsik** [comment]
Does that mean our project does not use the magnetometer? Why?

**Comment by cjackie** [comment]
Because the paper did not use magnetometer. And for prediction, I only used accelerometer. 

We could include magnetometer. But for now, it seems like not necessary.

**Comment by cjackie** [comment]
suggestions?

**Comment by kbumsik** [comment]
I see. The magnetometer's value depends on relative direction against the magnetic field so it may be highly inaccurate for this project...
But I would like to just store data for now. Storing magnetometer data doesn't give us much workload anyway.

**Comment by kbumsik** [comment]
BTW, although we split them into two classes, shouldn't they have the same timestamp?
