### ISSUE TITLE
Server API

### ISSUE THREAD

**Issue by cjackie** [cjackie/ActivitiesPrediction#7]
the APIs are specified by [here](https://github.com/cjackie/ActivitiesPrediction/edit/master/doc/design.md)

we should change the send message to:
```
SEND <type> <length of payload> <label> [body position]\LF
<CSV file payload>
```
and type is either 'accelerometer' or 'gyroscope'.

CSV file payload
```
timestamp1, x1, y1, z1
timestamp2, x2, y2, z2
.
.
```

**Comment by kbumsik** [comment]
As I mentioned at #6 , shouldn't they have the same timestamp anyway? Just like the sampled data from the internet?
